### ISSUE TITLE
Evil-Droid L HOST Plz help

### ISSUE THREAD

**Issue by cheeseinfusedDildo** [M4sc3r4n0/Evil-Droid#11]
I have a problem evry time i want to make one of these 

[1] APK MSF                                     
[2] BACKDOOR APK ORIGINAL (OLD)                 
[3] BACKDOOR APK ORIGINAL (NEW)                 
[4] BYPASS AV APK (ICON CHANGE)

and for instance a (BYPASS AV APK )
i need my local-ip  ad i know for a fact it should say my local ip at the top.
But it doesnt and iam very confused cuz i dont know why and i can't find any one else with this prob 

It says: Your-Local-ip: 0 ; Your-Public-ip: 62.195.Secret;

i realy cant figure this out and i need help 
Thank you for your time,And With sincere thanks,
Justice.A

**Comment by M4sc3r4n0** [comment]
i will fix it ..
