### ISSUE TITLE
[Solved]Not able to Use "Bypass AV Apk (Icon Change)"

### ISSUE THREAD

**Issue by back2Lobby** [M4sc3r4n0/Evil-Droid#13]
Whenever , I use this option , I get the following response! 

mv: cannot stat 'payload/smali/com/metasploit': No such file or directory
mv: cannot stat 'payload/smali/com/qrwzeiquvo/stage': No such file or directory
mv: cannot stat 'payload/smali/com/qrwzeiquvo/gtbrknfxvo/Payload.smali': No such file or directory
sed: can't read payload/smali/com/qrwzeiquvo/gtbrknfxvo/*: No such file or directory
sed: can't read payload/smali/com/qrwzeiquvo/gtbrknfxvo/*: No such file or directory
sed: can't read payload/smali/com/qrwzeiquvo/gtbrknfxvo/ronaawzqte.smali: No such file or directory
sed: can't read payload/smali/com/qrwzeiquvo/gtbrknfxvo/ronaawzqte.smali: No such file or directory
sed: can't read payload/AndroidManifest.xml: No such file or directory
sed: can't read payload/AndroidManifest.xml: No such file or directory
sed: can't read payload/res/values/strings.xml: No such file or directory
sed: can't read payload/AndroidManifest.xml: No such file or directory
sed: can't read payload/AndroidManifest.xml: No such file or directory
 
[*] Changing name and icon payload...
[ +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++  ]sed: can't read /root/Downloads/Evil-Droid-master/payload/AndroidManifest.xml: No such file or directory
sed: can't read /root/Downloads/Evil-Droid-master/payload/res/values/strings.xml: No such file or directory
mkdir: cannot create directory ‘/root/Downloads/Evil-Droid-master/payload/res/drawable’: No such file or directory
cp: cannot create regular file '/root/Downloads/Evil-Droid-master/payload/res/drawable/main_icon.png': No such file or directory
[ +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++  ] 
[*] Rebuilding APK file...
[ +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++  ] 
[*] Checking for ~/.android/debug.keystore for signing...
[ ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ ] 
[*] Attempting to sign the package with your android debug key
[ ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ ]
[*] Verifying signed artifacts...
[ +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++  ] 
[!] Failed to verify signed artifacts

**Comment by jeghuz** [comment]
Hello I can help you

**Comment by jeghuz** [comment]
Don't give any space for output file name

Eg: Google chrome.apk

       Change to

       Googlechrome.apk

**Comment by back2Lobby** [comment]
> Don't give any space for output file name
> 
> Eg: Google chrome.apk
> 
> ```
>    Change to
> 
>    Googlechrome.apk
> ```

Thanks Bro. It worked!!!!

**Comment by jeghuz** [comment]
Welcome broi

**Comment by Thandibirani** [comment]
solved
