### ISSUE TITLE
Help  [ X ] Debug key not found. Generating one now...   

### ISSUE THREAD

**Issue by Josue291997** [M4sc3r4n0/Evil-Droid#75]
[ ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++   ]                          
[*] Generating apk payload                                                                
[ +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++  ]                          
[*] Removing 1.apk framework file...                                                      
[ +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++  ]                          
[*] Decompiling Original APK...                                                           
[ +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++  ]                          
[*] Decompiling Payload APK...                                                            
[ +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++  ]                          
[*] Adding permission and Hook Smali                                                      
[ +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++  ]                          
##################################################################
inject Smali: com/disruptorbeam/gota/utils/ApplicationContextProvider.smali
In line:19
##################################################################
[ ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++   ] 
[*] Rebuilding Backdoored APK...                                                          
[ +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++  ]                          
[*] Checking for ~/.android/debug.keystore for signing...                                 
[ +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++  ]                          
 [ X ] Debug key not found. Generating one now...                                         
[ ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ ]                          
¿Cuáles son su nombre y su apellido?                                                      
  [Unknown]:

**Comment by nakamurahackit** [comment]
how to fix?

**Comment by Maxime-e** [comment]
> how to fix?

hello do you find the solution ?
